// Mocks generated by Mockito 5.4.5 from annotations
// in jobsit/test/features/auth/domain/usecases/login_user_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;

import 'package:dart_either/dart_either.dart' as _i4;
import 'package:jobsit/core/error/failures.dart' as _i5;
import 'package:jobsit/features/auth/domain/entities/user.dart' as _i6;
import 'package:jobsit/features/auth/domain/repositories/auth_repository.dart'
    as _i2;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i7;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

/// A class which mocks [AuthRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockAuthRepository extends _i1.Mock implements _i2.AuthRepository {
  MockAuthRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<_i4.Either<_i5.Failure, _i6.RegisteredUser>> registerUser({
    required String? email,
    required String? password,
    required String? firstName,
    required String? lastName,
    required String? phone,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#registerUser, [], {
              #email: email,
              #password: password,
              #firstName: firstName,
              #lastName: lastName,
              #phone: phone,
            }),
            returnValue:
                _i3.Future<_i4.Either<_i5.Failure, _i6.RegisteredUser>>.value(
                  _i7.dummyValue<_i4.Either<_i5.Failure, _i6.RegisteredUser>>(
                    this,
                    Invocation.method(#registerUser, [], {
                      #email: email,
                      #password: password,
                      #firstName: firstName,
                      #lastName: lastName,
                      #phone: phone,
                    }),
                  ),
                ),
          )
          as _i3.Future<_i4.Either<_i5.Failure, _i6.RegisteredUser>>);

  @override
  _i3.Future<_i4.Either<_i5.Failure, _i6.User>> loginUser({
    required String? email,
    required String? password,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#loginUser, [], {
              #email: email,
              #password: password,
            }),
            returnValue: _i3.Future<_i4.Either<_i5.Failure, _i6.User>>.value(
              _i7.dummyValue<_i4.Either<_i5.Failure, _i6.User>>(
                this,
                Invocation.method(#loginUser, [], {
                  #email: email,
                  #password: password,
                }),
              ),
            ),
          )
          as _i3.Future<_i4.Either<_i5.Failure, _i6.User>>);

  @override
  _i3.Future<_i4.Either<_i5.Failure, _i5.Success>> sendMail({
    required String? email,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#sendMail, [], {#email: email}),
            returnValue: _i3.Future<_i4.Either<_i5.Failure, _i5.Success>>.value(
              _i7.dummyValue<_i4.Either<_i5.Failure, _i5.Success>>(
                this,
                Invocation.method(#sendMail, [], {#email: email}),
              ),
            ),
          )
          as _i3.Future<_i4.Either<_i5.Failure, _i5.Success>>);

  @override
  _i3.Future<_i4.Either<_i5.Failure, _i5.Success>> verifyOtp({
    required String? otp,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#verifyOtp, [], {#otp: otp}),
            returnValue: _i3.Future<_i4.Either<_i5.Failure, _i5.Success>>.value(
              _i7.dummyValue<_i4.Either<_i5.Failure, _i5.Success>>(
                this,
                Invocation.method(#verifyOtp, [], {#otp: otp}),
              ),
            ),
          )
          as _i3.Future<_i4.Either<_i5.Failure, _i5.Success>>);
}
